import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../components/navbar";
import Image from "next/image";
import carImage from "../assets/icons/car-green.svg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ height: "100vh", overflow: "hidden" }}
      >
        <div className="layout">
          <Navbar />
          <main className="children-container">{children}</main>
          <div className="image-container">
            <Image src={carImage} alt="car image" />
          </div>
        </div>
      </body>
    </html>
  );
}
